export const ADD_COUNTER = 'ADD_COUNTER'
export const SET_ASYNC_STATUS = 'SET_ASYNC_STATUS'
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const IS_FETCHING = 'IS_FETCHING'
export const FETCHED = 'FETCHED'
export const REFRESG_FEED_CASH = 'REFRESG_FEED_CASH'



