export const ADD_COUNTER = 'ADD_COUNTER'
export const SET_ASYNC_STATUS = 'SET_ASYNC_STATUS'
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const IS_FETCHING = 'IS_FETCHING'

export const IS_LOGIN_FETCHING = 'IS_LOGIN_FETCHING'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'
export const LOG_OUT = 'LOG_OUT'


export const FETCHED = 'FETCHED'
export const REFRESG_FEED_CASH = 'REFRESG_FEED_CASH'
export const CLEAR_CASH = 'CLEAR_CASH'
export const FETCH_ALL_WITH_CLEAR = 'FETCH_ALL_WITH_CLEAR'
export const FETCH_ERR = 'FETCH_ERR'
export const FETCH_ERR_TEXT = 'FETCH_ERR_TEXT'

export const FONT_LOAD = 'FONT_LOAD'

export const SET_ACTIVE_PLAN = 'SET_ACTIVE_PLAN'


